version: '3.8'

services:
  db:
    image: postgres:15
    container_name: crypto_db
    restart: always
    environment:
      POSTGRES_USER: ria_admin
      POSTGRES_PASSWORD: dhPPRAJxDl4fH2hA
      POSTGRES_DB: crypto_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tracker:
    build: .
    container_name: crypto_tracker_app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

volumes:
  postgres_data:

